apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment-2020.05.29-DEV01.fullname" . }}
  labels:
    {{- include "deployment-2020.05.29-DEV01.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deployment-2020.05.29-DEV01.selectorLabels" . | nindent 4 }}
